# =====================================================
# docker-compose.yml - Cudos Network Deployment
# =====================================================
version: '3.8'

services:
  # CivicXAI Gateway Service
  civicxai-gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    container_name: civicxai-gateway
    ports:
      - "8080:8080"  # API port
      - "8000:8000"  # Agent port
    environment:
      - GATEWAY_AGENT_SEED=${GATEWAY_AGENT_SEED}
      - GATEWAY_AGENT_PORT=8000
      - API_PORT=8080
      - AI_PROVIDER_AGENT_ADDRESS=${AI_PROVIDER_AGENT_ADDRESS}
      - AGENT_NETWORK=${AGENT_NETWORK:-testnet}
      - MAX_FILE_SIZE=10485760
      - UPLOAD_DIR=/app/uploads
      - CACHE_DIR=/app/cache
    volumes:
      - ./uploads:/app/uploads
      - ./cache:/app/cache
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - cudos-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # CivicXAI Provider Service
  civicxai-provider:
    build:
      context: .
      dockerfile: Dockerfile.provider
    container_name: civicxai-provider
    ports:
      - "8001:8001"  # Agent port
    environment:
      - PROVIDER_AGENT_SEED=${PROVIDER_AGENT_SEED}
      - PROVIDER_AGENT_PORT=8001
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - CLAUDE_MODEL=${CLAUDE_MODEL:-claude-sonnet-4-5-20250929}
      - GATEWAY_AGENT_ADDRESS=${GATEWAY_AGENT_ADDRESS}
      - AGENT_NETWORK=${AGENT_NETWORK:-testnet}
      - CUDOS_NETWORK=${CUDOS_NETWORK:-testnet}
      - CUDOS_RPC_ENDPOINT=${CUDOS_RPC_ENDPOINT:-https://rpc.testnet.cudos.org}
      - CUDOS_REST_ENDPOINT=${CUDOS_REST_ENDPOINT:-https://rest.testnet.cudos.org}
      - MAX_CONCURRENT_REQUESTS=5
      - REQUEST_TIMEOUT=120
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - cudos-network
    depends_on:
      - civicxai-gateway

  # Cudos Full Node (Optional - for production)
  cudos-node:
    image: cudos/node:latest
    container_name: cudos-full-node
    ports:
      - "26656:26656"  # P2P
      - "26657:26657"  # RPC
      - "1317:1317"    # REST API
      - "9090:9090"    # gRPC
    environment:
      - CUDOS_NETWORK=${CUDOS_NETWORK:-testnet}
      - MONIKER=civicxai-node
      - CHAIN_ID=${CHAIN_ID:-cudos-testnet-public-3}
    volumes:
      - cudos-data:/root/.cudos
      - ./config/cudos:/config
    restart: unless-stopped
    networks:
      - cudos-network
    profiles:
      - production  # Only run with --profile production

networks:
  cudos-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

volumes:
  cudos-data:
    driver: local