# Generated by Django 5.2.7 on 2025-10-21 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explainable_ai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('source_type', models.CharField(choices=[('pdf', 'PDF Document'), ('url', 'Website Link'), ('document', 'Text Document')], max_length=20)),
                ('category', models.CharField(choices=[('policy', 'Policy Document'), ('research', 'Research Paper'), ('data', 'Data Source'), ('guideline', 'Guideline'), ('report', 'Report'), ('reference', 'Reference Material'), ('other', 'Other')], default='reference', max_length=50)),
                ('url', models.URLField(blank=True, help_text='URL for websites or online documents', max_length=500, null=True)),
                ('file', models.FileField(blank=True, help_text='Upload PDF or document', null=True, upload_to='data_sources/')),
                ('author', models.CharField(blank=True, max_length=255)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
                ('summary', models.TextField(blank=True, help_text='AI-generated or manual summary of content')),
                ('key_points', models.TextField(blank=True, help_text='Key takeaways, one per line')),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.IntegerField(default=0, help_text='Number of times referenced by AI')),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_sources_added', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source_type', 'category'], name='explainable_source__01ed1d_idx'), models.Index(fields=['is_active'], name='explainable_is_acti_66dc8b_idx')],
            },
        ),
    ]
